"""Render the computed scope as an HTML report + Jira-comment preview.

Everything rendered here was decided upstream by rules; this module only formats.
The Jira comment text is AI seam 2's slot — for v0.1 it is a deterministic template.
Unplug the AI and the correct scope still exists (this is that JSON, formatted).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from html import escape as esc

from .diff import DiffScope
from .history import Recurrence
from .loom_client import Symbol
from .risk import SymbolRisk
from .screens import Endpoint

GUIDANCE = {
    "GET": ("screen loads and lists/filters data correctly",
            "empty result set; invalid or missing query params; unauthorized access"),
    "POST": ("create/submit succeeds and the new entity appears in follow-up reads",
             "invalid payload rejected with a clear error; duplicate submission; unauthorized"),
    "PUT": ("edit saves and the change persists after reload",
            "update of a nonexistent or stale id; partial payload; unauthorized"),
    "PATCH": ("partial edit saves and persists after reload",
              "patch of a nonexistent id; conflicting concurrent edit; unauthorized"),
    "DELETE": ("delete removes the entity and dependent views update",
               "delete of a nonexistent or still-referenced entity; unauthorized"),
    "ANY": ("core flow of this endpoint completes", "invalid input; unauthorized access"),
}

BADGE = {"HIGH": "#c62828", "MEDIUM": "#e65100", "LOW": "#2e7d32"}


@dataclass
class Feature:
    screen: str
    endpoints: list[Endpoint]
    level: str
    reasons: list[str]
    min_depth: int
    inferred: bool
    via: list[str] = field(default_factory=list)  # changed symbol names reaching this feature

    @property
    def confidence(self) -> str:
        return "inferred" if self.inferred else "confirmed"


def _guidance(f: Feature) -> list[tuple[str, str, str]]:
    out = []
    for ep in sorted(set((e.verb, e.url) for e in f.endpoints)):
        happy, bad = GUIDANCE.get(ep[0], GUIDANCE["ANY"])
        out.append((f"{ep[0]} {ep[1]}", happy, bad))
    return out


# ---------------------------------------------------------------- Jira text

def jira_comment(
    scope: DiffScope, features: list[Feature], recs: list[Recurrence], ai_notes: str | None = None
) -> str:
    """The comment that would be posted to Jira.

    Deterministic anchors (scope, recurrence, order) are always present — those are the
    facts. When the investigator agent ran, its grounded per-screen test steps become the
    body (they vary run to run because the agent reads the actual current code). With
    --no-ai it falls back to the one-line-per-feature template.
    """
    order_key = {"HIGH": 2, "MEDIUM": 1, "LOW": 0}
    lines = [
        f"Regression scope for {scope.target_ref} (vs {scope.base_ref[:8]}) — generated by Tracer",
    ]
    if recs:  # the hero fact, always first — deterministic, cite-able
        lines += ["", "BUG HISTORY — this change re-touches previously-fixed code:"]
        for r in recs:
            lines.append(f"  • {r.path.rsplit('/', 1)[-1]}:{r.start}-{r.end} was fixed by {r.sha} “{r.subject}”")
        lines.append("  Test those prior bug scenarios hard — the same class of bug can return.")

    if ai_notes:  # grounded, varying body from the code-reading agent
        lines += ["", "WHAT TO TEST (read from the actual changed code):", "", ai_notes]
    else:  # --no-ai: deterministic one-liner per feature
        lines += ["", "FEATURES TO TEST (screens reachable from this change):"]
        for f in sorted(features, key=lambda f: (-order_key[f.level], f.min_depth)):
            hop = "changed directly" if f.min_depth == 0 else f"via {f.min_depth} hop{'s' * (f.min_depth > 1)}"
            lines.append(f"  • {f.screen} [{f.level}] ({hop}, reachability {f.confidence})")
            lines.append(f"      why: {f.reasons[0]}")

    order = [f.screen for f in features if f.level == "HIGH"] or [f.screen for f in features[:1]]
    if order:
        lines += ["", f"SUGGESTED TEST ORDER — start with: {', '.join(dict.fromkeys(order))}."]
    return "\n".join(lines)


# ---------------------------------------------------------------- HTML

def _sec(title: str, body: str) -> str:
    return f"<section><h2>{esc(title)}</h2>{body}</section>"


def jira_tickets_html(tickets) -> str:
    """Mock Jira ticket tree: parent Story + sub-tickets mapped to modules/screens."""
    if not tickets:
        return ""
    parent, subs = tickets
    rows = ""
    for t in subs:
        fix_badge = " <span class='badge' style='background:#6a1b9a'>FIX</span>" if t.is_fix else ""
        rows += (
            "<tr>"
            f"<td><code>{esc(t.key)}</code>{fix_badge}</td>"
            f"<td>{esc(t.summary)}<br><small>commit {esc(t.commit or '')}</small></td>"
            f"<td><span class='badge' style='background:{BADGE[t.risk]}'>{t.risk}</span></td>"
            f"<td>{esc(', '.join(t.modules) or '—')}</td>"
            f"<td>{esc(', '.join(t.screens) or '—')}</td></tr>"
        )
    body = (
        f"<p class='meta'>Parent <code>{esc(parent.key)}</code> — <b>{esc(parent.summary)}</b> "
        f"<span class='badge' style='background:{BADGE[parent.risk]}'>{parent.risk}</span><br>"
        f"<small>Modules: {esc(', '.join(parent.modules) or '—')} · "
        f"Screens to regression-test: {esc(', '.join(parent.screens) or '—')}</small></p>"
        "<table><tr><th>Sub-task</th><th>Commit / summary</th><th>Risk</th>"
        "<th>Modules</th><th>Screens to test</th></tr>" + rows + "</table>"
        "<p class='low-note'>Mock preview — not posted. <b>FIX</b> sub-tasks are where "
        "regressions hide; test their mapped screens hardest.</p>"
    )
    return _sec("Mock Jira — regression tickets (parent + sub-tasks mapped to screens)", body)


def bridge_html(bridge, endpoint_risk: dict[str, str] | None) -> str:
    """Cross-repo section: backend endpoint → real Angular screen (inferred), + unmapped gap."""
    if bridge is None:
        return ""
    endpoint_risk = endpoint_risk or {}
    rows = ""
    for m in sorted(bridge.mappings, key=lambda m: m.screen_name):
        lvl = endpoint_risk.get(m.endpoint.node_id, "LOW")
        rows += (
            "<tr>"
            f"<td><b>{esc(m.screen_name)}</b><br><small>{esc(m.client_component)}</small></td>"
            f"<td><span class='badge' style='background:{BADGE[lvl]}'>{lvl}</span></td>"
            f"<td><code>{esc(m.endpoint.verb)} {esc(m.endpoint.url)}</code></td>"
            f"<td><small class='inferred'>{esc(m.confidence)}</small></td></tr>"
        )
    mapped = (
        "<table><tr><th>Frontend screen</th><th>Risk (from server)</th>"
        "<th>Backend endpoint</th><th>Confidence</th></tr>" + rows + "</table>"
        if rows else "<p>No backend endpoint resolved to a client screen.</p>"
    )
    gap = ""
    if bridge.unresolved:
        items = "".join(
            f"<li><code>{esc(e.verb)} {esc(e.url)}</code> <small>{esc(e.screen)}</small></li>"
            for e in bridge.unresolved
        )
        gap = (
            "<p class='low-note'><b>Unmapped endpoints</b> — no client call site matched (internal / "
            "gRPC / cron API, or a dynamic client URL built via a helper). QA has no frontend screen "
            f"for these; they are backend surfaces.</p><ul>{items}</ul>"
        )
    body = (
        f"<p class='meta'>Match rate <b>{bridge.match_rate:.0%}</b> — "
        f"{len(bridge.mappings)} screen mapping(s), {len(bridge.unresolved)} unmapped. "
        "Cross-repo hops are always <span class='inferred'>inferred</span> (deterministic route join, "
        "not a confirmed call path).</p>" + mapped + gap
    )
    return _sec("Frontend screens to test (cross-repo — server → Angular)", body)


def render_html(
    scope: DiffScope,
    changed: list[SymbolRisk],
    features: list[Feature],
    recs: list[Recurrence],
    coupled: dict[str, list[tuple[str, float]]],
    tests: list[Symbol],
    blind_spots: list[Symbol] | None = None,
    ai_notes: str | None = None,
    tickets=None,
    bridge=None,
    endpoint_risk: dict[str, str] | None = None,
) -> str:
    feats = sorted(features, key=lambda f: (-{"HIGH": 2, "MEDIUM": 1, "LOW": 0}[f.level], f.min_depth))

    hero = ""
    if recs:
        items = "".join(
            f"<li><code>{esc(r.path.rsplit('/', 1)[-1])}:{r.start}–{r.end}</code> was fixed by "
            f"<code>{esc(r.sha)}</code> ({esc(r.date)}): <b>{esc(r.subject)}</b></li>"
            for r in recs
        )
        hero = (
            '<div class="hero"><h2>⚠ Defect recurrence — this change re-touches previously-fixed code</h2>'
            f"<ul>{items}</ul>"
            "<p>The same class of bug can return. Re-run the original bug's scenario as a first-class test.</p></div>"
        )

    feat_rows = ""
    for f in feats:
        hop = "changed directly" if f.min_depth == 0 else f"{f.min_depth} hop{'s' * (f.min_depth > 1)}"
        guide = "".join(
            f"<div class='guide'><code>{esc(ep)}</code><br>✅ <i>Happy:</i> {esc(h)}<br>❌ <i>Bad:</i> {esc(b)}</div>"
            for ep, h, b in _guidance(f)
        )
        feat_rows += (
            "<tr>"
            f"<td><b>{esc(f.screen)}</b><br><small>via {esc(', '.join(f.via[:4]))}</small></td>"
            f"<td><span class='badge' style='background:{BADGE[f.level]}'>{f.level}</span></td>"
            f"<td>{esc(hop)}<br><small class='{f.confidence}'>{f.confidence}</small></td>"
            f"<td><ul>{''.join(f'<li>{esc(r)}</li>' for r in f.reasons)}</ul></td>"
            f"<td>{guide}</td></tr>"
        )
    LOW_NOTE = (
        "<p class='low-note'><b>LOW risk</b> = defer these to your periodic full regression pass "
        "&#8212; not a signal to skip them. Static reachability analysis carries an inherent ~3% "
        "unsafe-skip rate; Tracer never promises a safe skip.</p>"
    )
    features_html = (
        "<table><tr><th>Feature / screen</th><th>Risk</th><th>Reachability</th><th>Why (cited)</th>"
        "<th>Regression guidance</th></tr>" + feat_rows + "</table>" + LOW_NOTE
        if feat_rows else "<p>No controller endpoints reached — see changed symbols below.</p>"
    )

    sym_rows = "".join(
        "<tr>"
        f"<td><code>{esc(r.symbol.name.rsplit('.', 1)[-1])}</code><br><small>{esc(r.symbol.path)}</small></td>"
        f"<td>{r.symbol.start_line}–{r.symbol.end_line}</td>"
        f"<td><span class='badge' style='background:{BADGE[r.level]}'>{r.level}</span></td>"
        f"<td><ul>{''.join(f'<li>{esc(x)}</li>' for x in r.reasons)}</ul></td></tr>"
        for r in changed
    )
    changed_html = "<table><tr><th>Changed symbol</th><th>Lines</th><th>Risk</th><th>Why</th></tr>" + sym_rows + "</table>"

    coupled_html = "".join(
        f"<li><code>{esc(f)}</code> historically co-changes with " +
        ", ".join(f"<code>{esc(o)}</code> ({freq:.0%})" for o, freq in others) + "</li>"
        for f, others in coupled.items() if others
    )
    coupled_html = f"<ul>{coupled_html}</ul>" if coupled_html else "<p>No strong co-change signals.</p>"

    tests_html = (
        "<ul>" + "".join(
            f"<li><code>{esc(t.name.rsplit('.', 1)[-1])}</code> <small>{esc(t.path)}</small></li>" for t in tests
        ) + "</ul>"
        if tests else "<p>No linked tests found for the changed symbols (Loom TESTED_BY).</p>"
    )

    blind_html = ""
    if blind_spots:
        items = "".join(
            f"<li><code>{esc(s.name.rsplit('.', 1)[-1])}</code> "
            f"<small>{esc(s.path)}:{s.start_line}–{s.end_line}</small></li>"
            for s in blind_spots
        )
        blind_html = _sec(
            "Blind spots — reachable from this change but unreachable by QA",
            f"<p>These symbols are in the blast radius but have no controller endpoint "
            f"and no <code>TESTED_BY</code> test linked in Loom. "
            f"QA has no direct path to exercise them.</p><ul>{items}</ul>",
        )

    return f"""<!-- Tracer v0.1 regression report -->
<meta charset="utf-8">
<title>Tracer — {esc(scope.target_ref)}</title>
<style>
 body {{ font: 15px/1.5 -apple-system, Segoe UI, sans-serif; max-width: 1100px; margin: 2rem auto; padding: 0 1rem; color: #222; }}
 h1 {{ font-size: 1.5rem; }} h2 {{ font-size: 1.15rem; margin-top: 2rem; }}
 table {{ border-collapse: collapse; width: 100%; }}
 th, td {{ border: 1px solid #ddd; padding: .5rem .6rem; text-align: left; vertical-align: top; }}
 th {{ background: #f5f5f5; }}
 .badge {{ color: #fff; padding: .15rem .5rem; border-radius: 4px; font-size: .8rem; font-weight: 600; }}
 .hero {{ background: #fff3f3; border: 2px solid #c62828; border-radius: 8px; padding: .5rem 1.2rem; margin: 1.5rem 0; }}
 .hero h2 {{ color: #c62828; margin-top: .8rem; }}
 .inferred {{ color: #e65100; }} .confirmed {{ color: #2e7d32; }}
 .guide {{ margin-bottom: .6rem; }}
 pre {{ background: #f5f5f5; border: 1px solid #ddd; border-radius: 6px; padding: 1rem; overflow-x: auto; }}
 small {{ color: #666; }}
 .low-note {{ color: #555; font-size: .9rem; border-left: 3px solid #2e7d32; padding-left: .6rem; margin-top: .5rem; }}
 .meta {{ color: #555; }}
</style>
<h1>Tracer regression scope — <code>{esc(scope.target_ref)}</code></h1>
<p class="meta">Baseline <code>{esc(scope.base_ref[:12])}</code> → target <code>{esc(scope.target_ref)}</code> ·
 {scope.total_files_changed} files changed, {len(scope.files)} backend files analyzed ·
 deterministic analysis (call graph + git history); reachability across DI/gRPC bridges is labeled
 <span class="inferred">inferred</span>, direct call paths <span class="confirmed">confirmed</span>.</p>
{_sec("Jira comment preview (what gets posted — grounded QA steps + cited facts)", f"<pre>{esc(jira_comment(scope, features, recs, ai_notes))}</pre>")}
{hero}
{jira_tickets_html(tickets)}
{bridge_html(bridge, endpoint_risk)}
{_sec("Features / screens to test", features_html)}
{_sec("Changed symbols", changed_html)}
{_sec("Historical co-change (watch for ripple effects)", coupled_html)}
{_sec("Linked tests to run first", tests_html)}
{blind_html}
"""
